language: rust
rust:
- nightly
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc --no-deps -p rust-mq -p mqttc -p mqtt3 &&
  echo "<meta http-equiv=refresh content=0;url=rustmq/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: da/J6tkOkOfdICIBkFOi3oRAc4mHRXOEtZNXcKNwFW+YvBWTVDwPHzKHJ15Qwcu01bydMBfL3lcMJkHvlNdd5j4F3XzWZmgsW2mGpeJYPxqvHcbzYCliGpQOLDmNKo+IQ5602X9x91QWf5OE/PYriTzoRdIWnyqcz6J2v5yEnxBvgLPSiQub6+lzcUlb7br4yerjfwdzVxG4ysz6riilASze8DLczDeu1Jnje/WWxd/nHRq2wJYgmPsqVFrI+ICuyA7r3nM0ZtFznzfPEOYrSLqSTVc4GSHynfSf7LylzgxsfaceVh2B41sVDCxwAEurUKsxTCZ/qlDXdlBKbsaitbWGDYcwuMy2r7XqQKfnZz0TgpyoCwYOSk2M/A8JdU7+QhU5BGSbU+nXmAtEtpsa067G1EqpZLKOW5FqGEQjJ9OlU+hdczq6Qrthmw4LzKmJQtld8iR9BYsL006v72bzv2Y0XGqViUmr8tSx5K7xjC8eJKiM8e1Gj1R9W4+sdyQNw0arIciLV4AeJWaVv8IuKsiSmiGT9nN+n2HCNFHlXqnCmRVqguCvB9r/cjSS++cj0qy3evQ8yk9FrK6CTJmSYmSNj3UJn+N/1iSWuHwL5TlknrfJ3Yvt+FF3GGf4XvQ7iEqFuszFsHioRucFEJl4h0WwTLuSY3vjYEf46luEKGw=
